// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPTM5etQu2p1QDwQ6nqrQ1qpCoVHBPHM',
    appId: '1:258967757141:android:3d3fb99f9fede17d920fdc',
    messagingSenderId: '258967757141',
    projectId: 'chronoapp-1fde1',
    storageBucket: 'chronoapp-1fde1.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2d_m-p0AYHsG0RqcSEXys5tleiYioAnM',
    appId: '1:258967757141:web:9317d040f439cd82920fdc',
    messagingSenderId: '258967757141',
    projectId: 'chronoapp-1fde1',
    authDomain: 'chronoapp-1fde1.firebaseapp.com',
    storageBucket: 'chronoapp-1fde1.appspot.com',
    measurementId: 'G-NB3XC5B88R',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2d_m-p0AYHsG0RqcSEXys5tleiYioAnM',
    appId: '1:258967757141:web:fa2e5ab1d0105efc920fdc',
    messagingSenderId: '258967757141',
    projectId: 'chronoapp-1fde1',
    authDomain: 'chronoapp-1fde1.firebaseapp.com',
    storageBucket: 'chronoapp-1fde1.appspot.com',
    measurementId: 'G-P55257HHKH',
  );

}